sudo: required
language: python
services:
- docker
before_install:
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- ls
script:
- echo "pass"
deploy:
  provider: script
  script: ./push_to_hub.sh
  on:
    all_branches: true
